site_name: Exordos Core
site_url: https://github.com/exordos/
repo_name: exordos_core
repo_url: https://github.com/exordos/exordos_core
edit_uri: browse/docs/
copyright: Copyright &copy; 2025-2026 Genesis Corporation

theme:
  name: zensical
  variant: modern
  language: en
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: lucide/moon
        name: Switch to light mode

plugins:
  - i18n:
      docs_structure: suffix
      fallback_to: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Russian
          build: true
  - search:
      lang:
        - en
        - ru
  - glightbox
  - render_swagger


extra:
  repo_icon: github
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Russian
      link: ./index.ru/
      lang: ru

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Software: index.md
  - Usage:
    - Local Deployment: usage/local_deployment.md
    - Admin Guide: usage/admin-guide.md
    - Security Guide: usage/security.md
    - Troubleshooting: usage/troubleshooting.md
    - Wizard: usage/wizard.md
  - Developer Guides:
    - Application Developer Guide: app-developer-guide/index.md
    - Core Developer Guide: core-developer-guide/index.md
    - Repo Proxy: core-developer-guide/repo-proxy.md
  - OpenAPI:
    - Boot API: openapi/openapi_boot.md
    - Orch API: openapi/openapi_orch.md
    - Status API: openapi/openapi_status.md
    - User API: openapi/openapi_user.md
  - Element:
    - Manifest: em/manifest.md
    - API: em/api_documentation.md
    - Service as a Service API: em/service.md
    - Example commands: em/cli.md
  - IAM:
    - Permissions Overview: iam/permissions_overview.md
  - Network:
    - Load Balancer as a Service API: network/load_balancer.md
  - Secrets:
      - Certificates: secret/certificates.md
